In [1]:
from utils import pre_process
from extraction import find_权宜处理_rule_base,find_一般政策语言_rule_base,find_设置特定目标_rule_base, find_执行过程规定_rule_base, find_评估标准_rule_base, 评估标准详细度_summurize, 向上级反映_rule_base

/Users/ender_yang/opt/anaconda3/envs/lainchain/lib/python3.9/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
docs = """
    【法宝引证码】 CLI.12.1541468
原文链接：https://www.pkulaw.com/lar/32f09a1c6c282205e761c51231946224bdfb.html
广东省住房和城乡建设厅关于印发环卫行业信用管理暂行办法的通知
广东省住房和城乡建设厅关于印发环卫行业信用管理暂行办法的通知

（粤建规范〔2019〕4号）

各地级以上市环境卫生主管部门：

　　现将《广东省住房和城乡建设厅关于环卫行业信用管理暂行办法》印发给你们，请认真组织实施。实施过程中遇到的问题，请径向省住房城乡建设厅反映。
广东省住房和城乡建设厅

2019年10月11日
　　广东省住房和城乡建设厅关于环卫行业信用管理暂行办法
　第一章　总　则
　　第一条　（目的依据）

　　为了规范广东省环卫行业秩序，建立生活垃圾处理运营单位信用体系，促进环卫行业健康、有序发展，根据《企业信息公示暂行条例》《广东省城乡生活垃圾处理条例》等相关法律法规，结合广东省环卫行业实际，制定本办法。
　　第二条　（适用范围）

　　在广东省行政区域内从事生活垃圾清扫、分类、收集、运输、处置等环卫服务活动的企业纳入信用管理范围。
　　第三条　（管理内容）

　　广东省环卫行业信用管理包括企业信用信息、项目信用综合考评、企业重点监管名单三项内容。
　　第四条　（管理原则）

　　环卫信用信息登记遵循公开、公平、公正的原则，以信用体系建设为主导，以政府监督管理为手段，以信用信息登记为载体，实行环卫信用管理制度，强化主体自律和社会监督，激发市场活力。
　　第五条　（管理部门和管理系统）

　　省住房城乡建设主管部门负责指导全省生活垃圾处理运营单位信用体系建设工作，建立和完善广东省环卫行业信用管理平台（以下简称“信用管理平台”）。

　　各地级以上市环境卫生主管部门根据管理权限对辖区内环卫企业的行为及信用信息实施管理，负责信用信息监管工作。

　第二章　信用信息管理
　　第六条　（信用信息采集、审核、录入、变更及注销）

　　各地级以上市环境卫生主管部门负责企业信用信息的采集、审核和录入，并及时对信用管理平台的信用信息进行变更和注销。
　　第七条　（信用信息明细）

　　信用信息包括企业名称、统一社会信用代码、法定代表人、委托单位、项目名称、项目负责人、项目地点、项目总额、服务期限、《广东省城市生活垃圾经营性清扫、收集、运输服务许可证》或《广东省城市生活垃圾经营性处置服务许可证》证书编号、证书有效期、联系电话等。
　　第八条　（责任落实）

　　各地级以上市环境卫生主管部门对其录入信用管理平台的信息真实性、客观性、完整性负责。
　　第九条　（信息公布）

　　各地级以上市环境卫生主管部门按照公开、公平、公正的原则，及时将企业信用信息和项目信用综合考评结果在信用管理平台公布，供各地级以上市环境卫生主管部门查询使用。

　第三章　项目信用综合考评
　　第十条　（考评单位）

　　纳入信用管理范围的企业，由各地级以上市环境卫生主管部门统一进行年度项目信用综合考评。
　　第十一条　（考评内容）

　　项目信用综合考评以企业履约能力、服务质量、遵纪守法三项指标作为考评内容。
　　第十二条　（考评等级）

　　项目信用综合考评等级分为优、良、差三个等级。
　　第十三条　（考评时间）

　　各地级以上市环境卫生主管部门在每年的1月完成上一年度的项目信用综合考评。

　第四章　监督管理
　　第十四条　（分级分类监管）

　　各地级以上市环境卫生主管部门根据企业的年度项目信用综合考评等级，实施分级分类监管，建立企业重点监管名单制度。

　　（一）全部项目信用综合考评等级为优的企业，纳入监管对象，实行动态监督管理，优先推荐参加政府招投标项目、评优评先活动；

　　（二）全部项目信用综合考评等级为良的企业，纳入监管的主要对象，实行常态化监督管理；

　　（三）项目信用综合考评为差的企业，列入重点监管名单，纳入重点监管对象，实行严格的日常监督检查；
　　第十五条　（重点监管名单认定）

　　企业在当年度有下列情况之一的，列入企业重点监管名单，期限为一年，主要包括：

　　（一）上一年度项目信用综合考评为差的；

　　（二）在环卫招标投标活动中存在违法行为且受到行政处罚的；

　　（三）发生较大及以上生产安全责任事故，或1年内累计发生2次及以上一般生产安全责任事故的； 

　　（四）违法运输、倾倒或处置生活垃圾，受到行政处罚的；

　　（五）拖欠工人工资拒不整改的。
　　第十六条　（认定录入）

　　各地级以上市环境卫生主管部门认定企业重点监管名单后，应在5个工作日内书面通知企业，并在10个工作日内登陆信用管理平台录入相关信息。
　　第十七条　（重点监管名单的移出）

　　列入重点监管名单的企业，自录入信用管理平台之日起一年内未再发生本办法第十五条规定的情形的，由项目所在地地级以上市环境卫生主管部门核准后移出企业重点监管名单。
　　第十八条　（异议处理）

　　企业对被列入重点监管名单有异议的，应当在收到书面通知之日起5个工作日内，向作出认定的部门提出书面复核申请。
　　第十九条　（复核处理）

　　各地级以上市环境卫生主管部门在收到企业提出的书面复核申请后5个工作日内进行复核并书面答复。

　第五章　附则
　　第二十条　（解释单位）

　　本办法由广东省住房和城乡建设厅负责解释。
　　第二十一条　（试行日期）

　　本办法自2019年10月10日起施行，有效期为3年。

　　广东省环卫信用信息登记表
企业名称
统一社会
信用代码
法定代表人
项目名称
委托单位
项目地点
项目总额
服务期限
许可证编号
许可证有效期
项目负责人
联系电话
项目委托单位意见
项目委托单位（盖章）：
年   月   日
地级以上市环境卫生主管
部门意见
地级以上市环境卫生主管部门（盖章）：
年   月   日

　　注：各地级以上市环境卫生主管部门负责采集、审核企业信用信息，并录入信用管理平台。

　　广东省环卫项目信用综合考评表
企业名称
项目名称
统一社会
信用代码
项目负责人
考评年度
联系电话
履约能力
是否存在违约行为        是□  否□
是否按期履行合同        是□  否□
综合履约能力            优□  良□  差□
服务质量
是否建立规章制度        是□  否□
是否发生安全生产事故    是□  否□
业主满意度              优□  良□  差□
遵纪守法
是否按规定为员工购买社保              是□  否□
是否按规定支付工人工资                是□  否□
是否受到各级环境卫生主管部门行政处罚  是□  否□
项目委托单位意见
项目委托单位（盖章）：
年   月   日
地级以上市环境卫生主管
部门意见
地级以上市环境卫生主管部门（盖章）：
年   月   日

　　注：（1）综合履约能力、业主满意度为“优”，且遵纪守法的企业考评等级为“优”。

　　（2）综合履约能力、业主满意度为“良”及以上但未达到全“优”，且遵纪守法的企业考评等级为“良”。

　　（3）综合履约能力、业主满意度为“差”，或发生违法违规行为的企业考评等级为“差”。

　　（4）发生违法违规行为的企业考评等级为“差”。

　　广东省环卫企业重点监管名单确认表
企业名称
项目名称
统一社会
信用代码
法定代表人
项目负责人
联系电话
1
上一年度项目信用综合考评为差的。
有□  无□
2
在环卫招标投标活动中存在违法行为且受到行政处罚的。
有□  无□
3
发生较大及以上生产安全责任事故，或1年内累计发生2次及以上一般生产安全责任事故的。
有□  无□
4
违法运输、倾倒或处置生活垃圾，受到行政处罚的。
有□  无□
5
拖欠工人工资拒不整改的。
有□  无□
项目委托单位意见
项目委托单位（盖章）：
年   月   日
地级以上市环境卫生主管
部门意见
地级以上市环境卫生主管部门（盖章）：
年   月   日

　　注：企业发生上述情况中的任意一项，经各地级以上市环境卫生主管部门确认即列入企业重点监管名单，期限为一年。

　　《广东省城市生活垃圾经营性清扫、收集、运输服务许可证》统计情况表
序号
法人名称
办公住所
设施地址
核准经营范围
核准经营车辆 
法定代表人
联系人
联系电话
许可证有效期
证书编号
申请日期
备注

　　《广东省城市生活垃圾经营性处置服务许可证》统计情况表
序号
法人名称
办公住所
设施地址
核准经营范围
核准经营规模（吨/年）
法定代表人
联系人
联系电话
许可证有效期
证书编号
申请日期
备注

　　餐厨垃圾收运企业情况表
地市
序号
企业名称
企业负责人
联系电话
业务范围
许可证
餐厨垃圾种类（餐饮垃圾、居民厨余垃圾、农贸市场有机易腐垃圾）
收集频次
收运方式
收运车辆数量与类型
收运
范围
收运
线路
备注
（次/天）
（直收直运/中转转运）
"""

In [3]:
matched_paragraphs_一般政策语言, matched_paragraphs_index = find_一般政策语言_rule_base(docs)

In [4]:
matched_paragraphs_一般政策语言

[('现将《广东省住房和城乡建设厅关于环卫行业信用管理暂行办法》印发给你们，请认真组织实施', '\u3000\u3000现将'),
 ('\u3000第一章\u3000总\u3000则', '总则/指导思想/基本原则'),
 ('\u3000\u3000第一条\u3000（目的依据）', '总则/指导思想/基本原则'),
 ('\u3000\u3000为了规范广东省环卫行业秩序，建立生活垃圾处理运营单位信用体系，促进环卫行业健康、有序发展，根据《企业信息公示暂行条例》《广东省城乡生活垃圾处理条例》等相关法律法规，结合广东省环卫行业实际，制定本办法',
  '总则/指导思想/基本原则'),
 ('\u3000\u3000第二条\u3000（适用范围）', '总则/指导思想/基本原则'),
 ('\u3000\u3000在广东省行政区域内从事生活垃圾清扫、分类、收集、运输、处置等环卫服务活动的企业纳入信用管理范围',
  '总则/指导思想/基本原则'),
 ('\u3000\u3000第三条\u3000（管理内容）', '总则/指导思想/基本原则'),
 ('\u3000\u3000广东省环卫行业信用管理包括企业信用信息、项目信用综合考评、企业重点监管名单三项内容', '总则/指导思想/基本原则'),
 ('\u3000\u3000第四条\u3000（管理原则）', '总则/指导思想/基本原则'),
 ('\u3000\u3000环卫信用信息登记遵循公开、公平、公正的原则，以信用体系建设为主导，以政府监督管理为手段，以信用信息登记为载体，实行环卫信用管理制度，强化主体自律和社会监督，激发市场活力',
  '总则/指导思想/基本原则'),
 ('\u3000\u3000第五条\u3000（管理部门和管理系统）', '总则/指导思想/基本原则'),
 ('\u3000\u3000省住房城乡建设主管部门负责指导全省生活垃圾处理运营单位信用体系建设工作，建立和完善广东省环卫行业信用管理平台（以下简称“信用管理平台”）',
  '总则/指导思想/基本原则'),
 ('\u3000\u3000各地级以上市环境卫生主管部门根据管理权限对辖区内环卫企业的行为及信用信息实施管理，负责信用信息监管工作',
  '总则/指导思想/基本原则')]

In [5]:
一般政策语言_list = []
一般政策语言_提取原因_list = []
for 一般政策语言, 一般政策语言_提取原因 in matched_paragraphs_一般政策语言:
    一般政策语言_list += [一般政策语言]
    一般政策语言_提取原因_list += [一般政策语言_提取原因]

In [6]:
一般政策语言_list

['现将《广东省住房和城乡建设厅关于环卫行业信用管理暂行办法》印发给你们，请认真组织实施',
 '\u3000第一章\u3000总\u3000则',
 '\u3000\u3000第一条\u3000（目的依据）',
 '\u3000\u3000为了规范广东省环卫行业秩序，建立生活垃圾处理运营单位信用体系，促进环卫行业健康、有序发展，根据《企业信息公示暂行条例》《广东省城乡生活垃圾处理条例》等相关法律法规，结合广东省环卫行业实际，制定本办法',
 '\u3000\u3000第二条\u3000（适用范围）',
 '\u3000\u3000在广东省行政区域内从事生活垃圾清扫、分类、收集、运输、处置等环卫服务活动的企业纳入信用管理范围',
 '\u3000\u3000第三条\u3000（管理内容）',
 '\u3000\u3000广东省环卫行业信用管理包括企业信用信息、项目信用综合考评、企业重点监管名单三项内容',
 '\u3000\u3000第四条\u3000（管理原则）',
 '\u3000\u3000环卫信用信息登记遵循公开、公平、公正的原则，以信用体系建设为主导，以政府监督管理为手段，以信用信息登记为载体，实行环卫信用管理制度，强化主体自律和社会监督，激发市场活力',
 '\u3000\u3000第五条\u3000（管理部门和管理系统）',
 '\u3000\u3000省住房城乡建设主管部门负责指导全省生活垃圾处理运营单位信用体系建设工作，建立和完善广东省环卫行业信用管理平台（以下简称“信用管理平台”）',
 '\u3000\u3000各地级以上市环境卫生主管部门根据管理权限对辖区内环卫企业的行为及信用信息实施管理，负责信用信息监管工作']

In [7]:
matched_paragraphs, matched_paragraphs_index = find_权宜处理_rule_base(docs, 一般政策语言_list)

In [8]:
matched_paragraphs

[]

In [9]:
matched_paragraphs, matched_paragraphs_index = find_设置特定目标_rule_base(docs, 一般政策语言_list)

In [10]:
matched_paragraphs

[('（2）综合履约能力、业主满意度为“良”及以上但未达到全“优”，且遵纪守法的企业考评等级为“良”', '达到')]

In [11]:
matched_paragraphs_执行过程规定, matched_paragraphs_index, content, first, last, length = find_执行过程规定_rule_base(docs, 一般政策语言_list)

In [12]:
content

['第八条\u3000（责任落实）',
 '\u3000\u3000各地级以上市环境卫生主管部门对其录入信用管理平台的信息真实性、客观性、完整性负责',
 '\u3000\u3000第九条\u3000（信息公布）',
 '\u3000\u3000各地级以上市环境卫生主管部门按照公开、公平、公正的原则，及时将企业信用信息和项目信用综合考评结果在信用管理平台公布，供各地级以上市环境卫生主管部门查询使用',
 '\u3000第三章\u3000项目信用综合考评',
 '\u3000\u3000第十条\u3000（考评单位）',
 '\u3000\u3000纳入信用管理范围的企业，由各地级以上市环境卫生主管部门统一进行年度项目信用综合考评',
 '\u3000\u3000第十一条\u3000（考评内容）',
 '\u3000\u3000项目信用综合考评以企业履约能力、服务质量、遵纪守法三项指标作为考评内容',
 '\u3000\u3000第十二条\u3000（考评等级）',
 '\u3000\u3000项目信用综合考评等级分为优、良、差三个等级',
 '\u3000\u3000第十三条\u3000（考评时间）',
 '\u3000\u3000各地级以上市环境卫生主管部门在每年的1月完成上一年度的项目信用综合考评',
 '\u3000第四章\u3000监督管理',
 '\u3000\u3000第十四条\u3000（分级分类监管）',
 '\u3000\u3000各地级以上市环境卫生主管部门根据企业的年度项目信用综合考评等级，实施分级分类监管，建立企业重点监管名单制度',
 '\u3000\u3000（一）全部项目信用综合考评等级为优的企业，纳入监管对象，实行动态监督管理，优先推荐参加政府招投标项目、评优评先活动；',
 '\u3000\u3000（二）全部项目信用综合考评等级为良的企业，纳入监管的主要对象，实行常态化监督管理；',
 '\u3000\u3000（三）项目信用综合考评为差的企业，列入重点监管名单，纳入重点监管对象，实行严格的日常监督检查；',
 '\u3000\u3000第十五条\u3000（重点监管名单认定）',
 '\u3000\u3000企业在当年度有下列情况之一的，列入企业重点监管名单，期限为一年，主要包括：',
 '\u3000\u3000（一）上一年度项目信用综合考评为差的；',
 '\u3000\u3000（二）在环卫招标投标活动中存在违法行为且受到行政处罚的；',
 '\u3000\u3000（三）发生较大及以上生产安全责任事故，或1年内累计发生2次及以上一般生产安全责任事故的； ',
 '\u3000\u3000（四）违法运输、倾倒或处置生活垃圾，受到行政处罚的；',
 '\u3000\u3000（五）拖欠工人工资拒不整改的',
 '\u3000\u3000第十六条\u3000（认定录入）',
 '\u3000\u3000各地级以上市环境卫生主管部门认定企业重点监管名单后，应在5个工作日内书面通知企业，并在10个工作日内登陆信用管理平台录入相关信息',
 '\u3000\u3000第十七条\u3000（重点监管名单的移出）',
 '\u3000\u3000列入重点监管名单的企业，自录入信用管理平台之日起一年内未再发生本办法第十五条规定的情形的，由项目所在地地级以上市环境卫生主管部门核准后移出企业重点监管名单',
 '\u3000\u3000第十八条\u3000（异议处理）',
 '\u3000\u3000企业对被列入重点监管名单有异议的，应当在收到书面通知之日起5个工作日内，向作出认定的部门提出书面复核申请',
 '\u3000\u3000第十九条\u3000（复核处理）',
 '\u3000\u3000各地级以上市环境卫生主管部门在收到企业提出的书面复核申请后5个工作日内进行复核并书面答复',
 '\u3000第五章\u3000附则',
 '\u3000\u3000第二十条\u3000（解释单位）',
 '\u3000\u3000本办法由广东省住房和城乡建设厅负责解释']

In [13]:
length

1191

In [14]:
matched_paragraphs, matched_paragraphs_index = find_评估标准_rule_base(docs)

In [15]:
matched_paragraphs

[('环卫信用信息登记遵循公开、公平、公正的原则，以信用体系建设为主导，以政府监督管理为手段，以信用信息登记为载体，实行环卫信用管理制度，强化主体自律和社会监督，激发市场活力',
  '监督'),
 ('\u3000第四章\u3000监督管理', '章节内容'),
 ('\u3000\u3000第十四条\u3000（分级分类监管）', '章节内容'),
 ('\u3000\u3000各地级以上市环境卫生主管部门根据企业的年度项目信用综合考评等级，实施分级分类监管，建立企业重点监管名单制度', '章节内容'),
 ('\u3000\u3000（一）全部项目信用综合考评等级为优的企业，纳入监管对象，实行动态监督管理，优先推荐参加政府招投标项目、评优评先活动；',
  '章节内容'),
 ('\u3000\u3000（二）全部项目信用综合考评等级为良的企业，纳入监管的主要对象，实行常态化监督管理；', '章节内容'),
 ('\u3000\u3000（三）项目信用综合考评为差的企业，列入重点监管名单，纳入重点监管对象，实行严格的日常监督检查；', '章节内容'),
 ('\u3000\u3000第十五条\u3000（重点监管名单认定）', '章节内容'),
 ('\u3000\u3000企业在当年度有下列情况之一的，列入企业重点监管名单，期限为一年，主要包括：', '章节内容'),
 ('\u3000\u3000（一）上一年度项目信用综合考评为差的；', '章节内容'),
 ('\u3000\u3000（二）在环卫招标投标活动中存在违法行为且受到行政处罚的；', '章节内容'),
 ('\u3000\u3000（三）发生较大及以上生产安全责任事故，或1年内累计发生2次及以上一般生产安全责任事故的； ', '章节内容'),
 ('\u3000\u3000（四）违法运输、倾倒或处置生活垃圾，受到行政处罚的；', '章节内容'),
 ('\u3000\u3000（五）拖欠工人工资拒不整改的', '章节内容'),
 ('\u3000\u3000第十六条\u3000（认定录入）', '章节内容'),
 ('\u3000\u3000各地级以上市环境卫生主管部门认定企业重点监管名单后，应在5个工作日内书面通知企业，并在10个工作日内登陆信用管理平台录入相关信息',
  '章节内容'),
 ('\u3000\u3000第十七条\u3000（重点监管名单的移出）', '章节内容'),
 ('\u3000\u3000列入重点监管名单的企业，自录入信用管理平台之日起一年内未再发生本办法第十五条规定的情形的，由项目所在地地级以上市环境卫生主管部门核准后移出企业重点监管名单',
  '章节内容'),
 ('\u3000\u3000第十八条\u3000（异议处理）', '章节内容'),
 ('\u3000\u3000企业对被列入重点监管名单有异议的，应当在收到书面通知之日起5个工作日内，向作出认定的部门提出书面复核申请', '章节内容'),
 ('\u3000\u3000第十九条\u3000（复核处理）', '章节内容'),
 ('\u3000\u3000各地级以上市环境卫生主管部门在收到企业提出的书面复核申请后5个工作日内进行复核并书面答复', '章节内容')]

In [16]:
matched_paragraphs, matched_paragraphs_index = 向上级反映_rule_base(docs)

In [17]:
matched_paragraphs

[('实施过程中遇到的问题，请径向省住房城乡建设厅反映', '请径向省住房城乡建设厅反映')]

In [18]:
import re
keyword = ["(在|于)(年|月|日)前"]
pattern = re.compile("|".join(keyword))

sentence = "于日前上交"
pattern.search(sentence)

In [19]:
import cn2an
number_chinese_pattern = re.compile(r'(?:(?:[一二三四五六七八九]十)?[一二三四五六七八九]|十[一二三四五六七八九]?|二十|三十|四十|五十|六十|七十|八十|九十)')
paragraph = "第三十一（"
number = re.search(number_chinese_pattern, paragraph).group()
index = paragraph.index(number)

number_int = cn2an.cn2an(number)
number_int += 1
target_number = cn2an.an2cn(number_int)

end_word = target_number + paragraph[index + len(number)]
end_word

'三十二（'

In [20]:
number_pattern = re.compile(r'\d+')
sentence = "第1条 坚决维护"
re.search(number_pattern, sentence)
number = re.search(number_pattern, sentence).group()
index = sentence.index(number)

target_number = str(int(number) + 1)
target_number = str(target_number)

end_word = target_number + sentence[index + len(number)]
end_word

'2条'

In [10]:
import sqlite3
import pandas as pd

file = "梧州市人民政府办公室关于进一步明确我市职业...(FBM-CLI.12.585959).txt"
db = "policies_all.db"

conn = sqlite3.connect(db)

sql = f"SELECT id, filename, dt FROM category WHERE filename = '{file}' "
df_sql = pd.read_sql_query(sql, conn)
文件名称 = df_sql["filename"][0]
法宝引证码 = df_sql["id"][0]
颁布时间 = df_sql["dt"][0]
颁布时间

''

In [11]:
颁布时间 = df_sql["dt"][1]
颁布时间

'2012.01.16'

In [6]:
sql = f"SELECT filename, COUNT(*) FROM category GROUP BY filename HAVING COUNT(*) > 1"
df = pd.read_sql_query(sql, conn)
df

                                               filename  COUNT(*)
0          2013年市属国有企业监事会工作指导意见(FBM-CLI.12.6755732).txt         2
1     2015年安徽省科技成果转化服务中心公开招聘人员...(FBM-CLI.12.4966453...         2
2      七台河市人民政府关于促进快递业发展的实施意...(FBM-CLI.12.1508403).txt         2
3      七台河市人民政府关于发布行政执法主体资格的...(FBM-CLI.12.1507699).txt         2
4      七台河市人民政府办公室关于印发《七台河市质...(FBM-CLI.12.1507681).txt         2
...                                                 ...       ...
3829   龙岩市人民政府关于下放、委托一批市级行政审...(FBM-CLI.12.3931889).txt         2
3830  龙岩市人民政府关于龙岩市2019年度第十五批次城...(FBM-CLI.12.3931887...         2
3831   龙岩市人民政府办公室关于印发龙岩地质公园管...(FBM-CLI.12.3931404).txt         2
3832   龙岩市人民政府办公室关于印发龙岩市红军标语...(FBM-CLI.12.1627854).txt         2
3833   龙岩市人民政府办公室关于印发龙岩市红军标语...(FBM-CLI.12.3931552).txt         2

[3834 rows x 2 columns]

In [7]:
for filename in df["filename"]:
    sql = f"SELECT id, filename, dt FROM category WHERE filename = '{filename}' "
    df_sql = pd.read_sql_query(sql, conn)
    if df_sql["dt"][0] != df_sql["dt"][1]:
        print(filename)

梧州市人民政府办公室关于进一步明确我市职业...(FBM-CLI.12.585959).txt

KeyboardInterrupt:

In [14]:
df

               id                                        filename          dt
0  CLI.12.1896252  14春季(13学年下学期)银行代收启动预公告(FBM-CLI.12.1896252).txt  2013.12.23